# Generated by Django 4.0.4 on 2022-05-30 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_together', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeuser',
            old_name='room_id',
            new_name='room_group',
        ),
    ]
